#!/bin/sh

set -eu

[ -d ".git" ]
[ -n "${DM_REPO-}" ]
[ -d "${DM_REPO}/.git" ]

NAME="$1"
COMMIT="$2"
OUT="$PWD/$NAME"

git -C "$DM_REPO" worktree add --detach --no-checkout -- "$OUT" "$COMMIT"
mv -- "$OUT/.git" "$OUT/.git.tmp"

# shellcheck disable=SC2041
for pathspec in 'FileCfg/*TemplateTb.json'; do
	git -C "$OUT" --git-dir ".git.tmp" checkout HEAD -- "$pathspec"
	git add -v -- "$NAME/$pathspec" > /dev/null
done

mv -- "$OUT/.git.tmp" "$OUT/.git"
git -C "$DM_REPO" worktree remove --force -- "$OUT"

git checkout -- "$NAME"

NPROC="$(nproc --ignore=1)"
# shellcheck disable=SC2016
git ls-files -z -- "$NAME/*.json" | xargs -0 -L1 -P "$NPROC" sh -c 'set -eu; jq . -- "$0" > /dev/null; jq . -- "$0" | sponge -- "$0"'
# shellcheck disable=SC1003,SC2016
git ls-files -z -- "$NAME" ':!:*.json' | xargs -0 -L1 -P "$NPROC" sed -i '$a\' -- || :
git ls-files -z -- "$NAME" ':!:*.json' | xargs -0 -L1 -P "$NPROC" dos2unix -q -- || :

git ls-files -z -- "$NAME" | xargs -0 git add -v --
