#!/bin/sh

set -eu

[ -d ".git" ]

: "${TRANSLATE_DM:=$HOME/git/translate-dm}"
(
	cd -- "$TRANSLATE_DM"
	go build
)

for dir in v*; do
	[ -d "$dir" ] || continue
	[ $# -eq 0 ] || case "$*" in
		*${dir}*) ;;
		*) continue ;;
	esac

	printf '%s\n' "$dir"
	hash="$(git log -1 --pretty='format:%H' --grep "^Add ${dir}$")"
	[ -n "$hash" ] || continue

	git checkout "$hash" -- "$dir"
	rm -v -- "$dir/info" 2> /dev/null || :
	"$TRANSLATE_DM/translate-dm" \
		--types "FileCfg:excel" \
		--dm "$dir" \
		--queries "$TRANSLATE_DM/queries/filecfg.yml" \
		--output "${dir}/translate.sed" |
		tee -- "$dir/info"

	if [ ! -s "$dir/translate.sed" ]; then
		printf 'E: translation failed at %s\n' "$dir"
		exit 1
	fi

	printf '%s\n' "Replacing $dir files"
	fd -g '*.json' "$dir" -x sed -i -f "$dir/translate.sed" --
	rm -- "$dir/translate.sed"

	printf '%s\n' "Updating git index"
	git add -- "$dir/FileCfg"
	if [ -z "$(git status --porcelain -- "$dir/FileCfg")" ]; then
		git checkout master -- "$dir/info"
	fi
done
